# Generated by Django 3.2.15 on 2022-09-30 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursevisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time_on', models.TimeField(auto_now=True)),
                ('visit_date_on', models.DateField(auto_now=True)),
                ('visit_time_to', models.TimeField(blank=True, null=True)),
                ('visit_date_to', models.DateField(blank=True, null=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
