# Generated by Django 3.2.15 on 2022-09-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursevisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevisitor',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
