# Generated by Django 3.2.15 on 2022-09-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursevisitor_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevisitor',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='coursevisitor',
            name='visit_date_to',
        ),
        migrations.RemoveField(
            model_name='coursevisitor',
            name='visit_time_to',
        ),
    ]
